# Generated by Django 5.2.7 on 2025-11-26 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('period', models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III')], max_length=4)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('cycle', models.PositiveIntegerField()),
                ('practical_hours', models.PositiveIntegerField(default=0)),
                ('theoretical_hours', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('aula', 'Aula'), ('laboratorio', 'Laboratorio')], max_length=20)),
                ('capacity', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rooms/')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('night', 'Noche')], max_length=20, unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CourseGroupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_groups', models.PositiveIntegerField(default=1)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_config', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSessionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('juntas', 'Juntas'), ('separadas', 'Separadas')], default='separadas', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session_policy', to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='PeriodPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('configuracion', 'Etapa de configuración'), ('creacion_horarios', 'Etapa de creación de horarios'), ('cambios', 'Etapa de cambios')], max_length=30)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.academicperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido paterno')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Apellido materno')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('roles', models.ManyToManyField(blank=True, related_name='people', to='auth.group')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.plan'),
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('shift', models.CharField(blank=True, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.course')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='api.room')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='api.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='api.school'),
        ),
        migrations.CreateModel(
            name='DepartmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_head_roles', to='api.person')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_heads', to='api.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_director_roles', to='api.person')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='api.school')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.site'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('contratado', 'Contratado'), ('nombrado', 'Nombrado'), ('asociado', 'Asociado')], max_length=20)),
                ('min_weekly_hours', models.PositiveIntegerField()),
                ('max_unavailability_hours', models.PositiveIntegerField(default=0, help_text='Horas máximas de indisponibilidad por semana')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('session_type', models.CharField(choices=[('teoria', 'Teoría'), ('practica', 'Práctica')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='api.coursegroup')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='api.room')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='api.teacher')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='api.teacher'),
        ),
        migrations.CreateModel(
            name='TeacherUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miércoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sábado')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='api.teacher')),
            ],
            options={
                'ordering': ['teacher', 'day', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CourseDayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('mon', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miércoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sábado'), ('sun', 'Domingo')], max_length=3)),
                ('preference', models.CharField(choices=[('prefer', 'Prefiere'), ('avoid', 'Evitar')], default='prefer', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_preferences', to='api.course')),
            ],
            options={
                'unique_together': {('course', 'day')},
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offering_type', models.CharField(choices=[('normal', 'Normal'), ('nivelacion', 'Nivelación'), ('vacacional', 'Vacacional')], default='normal', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('academic_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings', to='api.academicperiod')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='api.course')),
            ],
            options={
                'unique_together': {('course', 'academic_period', 'offering_type')},
            },
        ),
        migrations.CreateModel(
            name='CourseTeacherPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('alto', 'Alto'), ('normal', 'Normal'), ('baja', 'Baja'), ('nula', 'Nula')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_preferences', to='api.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_preferences', to='api.teacher')),
            ],
            options={
                'ordering': ['course', 'level'],
                'unique_together': {('course', 'teacher')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursegroup',
            unique_together={('course', 'code')},
        ),
    ]
