# Generated by Django 5.2.7 on 2025-11-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='room',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='teacher',
        ),
    ]
