# Generated by Django 5.2.7 on 2025-12-04 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseteacherpreference',
            options={'ordering': ['course', 'teacher']},
        ),
        migrations.RemoveField(
            model_name='coursedaypreference',
            name='preference',
        ),
        migrations.RemoveField(
            model_name='courseteacherpreference',
            name='level',
        ),
        migrations.CreateModel(
            name='ScheduleChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('cambio_vacio', 'Cambio a espacio vacío'), ('cambio_ocupado', 'Cambio a horario ocupado'), ('rechazo_curso', 'Rechazo de curso'), ('abrir_grupo', 'Abrir grupo')], max_length=20)),
                ('target_day', models.PositiveIntegerField(blank=True, null=True)),
                ('target_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('approvals', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='api.teacher')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to='api.schedule')),
                ('target_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.room')),
                ('target_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_for_requests', to='api.teacher')),
            ],
        ),
    ]
