# Generated by Django 5.2.7 on 2025-11-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_coursegroup_room_remove_coursegroup_shift_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='capacity',
        ),
    ]
