# Generated by Django 5.2.6 on 2025-12-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_courseteacherpreference_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseteacherpreference',
            name='notes',
        ),
    ]
