# Generated by Django 5.2.7 on 2025-11-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_coursegroup_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseoffering',
            name='capacity',
        ),
    ]
