# Generated by Django 5.2.7 on 2025-11-27 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_courseoffering_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseShiftPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('morning', 'Mañana'), ('afternoon', 'Tarde'), ('night', 'Noche')], max_length=20)),
                ('preference', models.CharField(choices=[('prefer', 'Prefiere'), ('avoid', 'Evitar')], default='prefer', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_preferences', to='api.course')),
            ],
            options={
                'unique_together': {('course', 'shift')},
            },
        ),
    ]
