# Generated by Django 5.2.7 on 2025-11-27 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_courseshiftpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTeacherPreferenceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('alto', 'Alto'), ('normal', 'Normal'), ('baja', 'Baja'), ('nula', 'Nula')], default='normal', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_requests', to='api.course')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preference_requests_reviewed', to='api.person')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_requests', to='api.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('course', 'teacher', 'status')},
            },
        ),
    ]
