# Generated by Django 5.2.7 on 2025-11-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_courseteacherpreferencerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_enabled', models.JSONField(default=list, help_text="Lista de días habilitados, ej: ['mon','tue','wed','thu','fri','sat']")),
                ('start_time', models.TimeField(help_text='Hora de inicio global permitida, ej: 06:00')),
                ('end_time', models.TimeField(help_text='Hora de fin global permitida, ej: 23:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseTeacherPreferenceRequest',
        ),
    ]
