# Generated by Django 5.2.7 on 2025-11-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_generalscheduleconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalscheduleconfig',
            name='days_enabled',
            field=models.CharField(choices=[('mon', 'Lunes'), ('tue', 'Martes'), ('wed', 'Miércoles'), ('thu', 'Jueves'), ('fri', 'Viernes'), ('sat', 'Sábado'), ('sun', 'Domingo')], help_text='Días habilitados separados por comas, ej: mon,tue,wed', max_length=50),
        ),
    ]
