# Generated by Django 5.2.7 on 2025-11-29 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_generalscheduleconfig_days_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalscheduleconfig',
            old_name='days_enabled',
            new_name='day_name',
        ),
    ]
