# Generated by Django 5.2.7 on 2025-11-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_days_enabled_generalscheduleconfig_day_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalscheduleconfig',
            name='day_name',
            field=models.CharField(choices=[('lunes', 'Lunes'), ('martes', 'Martes'), ('miércoles', 'Miércoles'), ('jueves', 'Jueves'), ('viernes', 'Viernes'), ('sábado', 'Sábado'), ('domingo', 'Domingo')], help_text='Días habilitados separados por comas, ej: mon,tue,wed', max_length=50),
        ),
    ]
